[project]
name = "ml-zoomcamp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "altair>=5.4.1",
    "arrow>=1.3.0",
    "flask>=3.0.3",
    "pandas>=2.2.3",
    "polars>=1.8.1",
    "pyarrow>=17.0.0",
    "scikit-learn>=1.5.2",
]

[project.scripts]
hello = "ml_zoomcamp:hello"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
dev-dependencies = [
    "iprogress>=0.4",
    "ipykernel>=6.29.5",
    "matplotlib>=3.9.2",
    "ruff>=0.6.7",
    "tqdm>=4.66.5",
]
